name: ci
on:
  push:
    branches:
      - master

jobs:
  dispatch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Post request
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PUSH_TOKEN }}
          script: |
            const repositry = "approvers/approvers.github.io"
            const workflowId = 2751281
            await github.request(`POST /repos/${repositry}/actions/workflows/${workflowId}/dispatches`, { ref: "main" })
